### PR TITLE
pkg/guid: Prefer passing GUID by value

### PR DESCRIPTION
**Pull request by kevpar**
Signed-off-by: Kevin Parsons <kevpar@microsoft.com>

### CODE REVIEW

**Comment by jterry75** [comment]
LGTM but why?

**Comment by kevpar** [comment]
@jterry75 I was discussing with @jstarks about when to use a GUID by value vs by reference, and we concluded it would be simpler to just use it by value everywhere. As another datapoint, Google's UUID package passes around its `[16]byte` array by value everywhere, which is equivalent to what we're doing here.

We will just need to pass it by reference to the native methods which expect a `LPCGUID`, but that shouldn't be a problem.

**Comment by jterry75** [comment]
I'm fine with it, it's more `go-ish` anyways I was just wondering since we are using `windows.GUID` and it's not `[16]byte`

**Comment by kevpar** [comment]
Yeah, it's kind of a compromise between Windows and Go semantics. Windows format, but prefer pass-by-value like Go.

**Pull request merged**
