### PR TITLE
Correct spelling in PipeConfig {Input,Output}BufferSize doc.

### PR DESCRIPTION
**Pull request by gbbr**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@kevpar ptal

**Comment by kevpar** [comment]
Hi @gbbr, can you please amend your commit and sign it with "git commit --amend -s". Otherwise this LGTM.

**Comment by gbbr** [comment]
Done

**Review by kevpar — APPROVED** [review]
Thanks! LGTM

**Comment by thaJeztah** [comment]
oh! missed that there's no DCO check on this repo; perhaps enable https://github.com/probot/dco on this repo?

**Pull request merged**
